name: Update WOOFi Metrics

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests pandas
      - name: Run WOOFi DefiLlama uploader
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: python woofi_defillama_to_dune.py
